"""add File model

Revision ID: fa73cd88b6d0
Revises: 
Create Date: 2026-01-18 22:09:18.297026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa73cd88b6d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('encrypted_name', sa.String(length=255), nullable=False),
    sa.Column('encrypted_path', sa.String(length=512), nullable=False),
    sa.Column('original_size', sa.Integer(), nullable=False),
    sa.Column('encrypted_size', sa.Integer(), nullable=False),
    sa.Column('original_hash', sa.String(length=128), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.func.current_timestamp(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_encrypted_name'), ['encrypted_name'], unique=False)

    op.create_table('file_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('max_downloads', sa.Integer(), nullable=False),
    sa.Column('downloads_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_links_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_links_token'))

    op.drop_table('file_links')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_encrypted_name'))

    op.drop_table('files')
    # ### end Alembic commands ###
